### ISSUE TITLE
Issues with new unit implementation

### ISSUE THREAD

**Issue by thomasp85** [thomasp85/grid#14] opened 2019-04-12 07:44 UTC
- [ ] 1)
```
* installing *source* package ‘augmentedRCBD’ ...
...
** byte-compile and prepare package for lazy loading
Error in get(x, envir = ns, inherits = FALSE) :
 object 'unit.list' not found
Error: unable to load R code in package ‘augmentedRCBD’
```
which I presume should be using the generic unit().

The problem is the resize_heights() function, which plays silly games to try to perform a unit subset assignment.  I think that this might be fixed by just relying on grid's unit subset assignment, but I need to test on R with the new-unit patch applied.

- [ ] 2)

Packages Gmisc ggfittext ggrepel ggstatplot: check class() assuming length 1, a bug in those packages.  We reported Gmisc: I will leave the others until this is live.

- [x] 3)
```
VECTOR_ELT() can only be applied to a 'list', not a 'double'
```
in many packages:
BAS CINNA DescribeDisplay EMMIXmfa GGally ICtest LDheatmap
PPforest SHELF StratigrapheR airGR auditor codebook  ggmcmc lemon
nzelect qualvar randomForestExplainer rrr specmine staRdom statVisual tsfeatures userfriendlyscience

GGally and codebook give some context:
```
Error in grid.Call.graphics(C_setviewport, vp, TRUE): VECTOR_ELT() can only be applied to a 'list', not a 'double'
```
as before.

- [x] 4)
```
 (list) object cannot be coerced to type 'double'
```
from unit() in ggpol.

- [x] 5)
```
REAL() can only be applied to a 'numeric', not a 'integer'
```
from Ops.units in IntNMF NMF SCROPIUS diceR iTOP pheatmap, seemingly all from NMF.

- [x] 6)
```
`heatmap_width` and `width` should not all be the absolute units.
```
from CNVScope armada countToFPKM eclust wilson

- [x] 7)
```
old version of unit class is no longer allowed
```
from fewer after reinstallation - MTLR SpatialBall firebehavioR foreSIGHT superheat xpose .  Some say from is.unit().

- [ ] 8)
```
Error in mm2pixels(convert(u, "mm")) : Unit must be in millimeters
```
from MendelianRandomization Miso PCRedux PPQplan Plasmidprofiler otsad autoplotly frailtyEM getTBinR gprofiler2 heatmaply manhattanly
neatmaps otsad personalized plotly rabhit trelliscopejs wilson

- [x] 9)
ParamHelpers segfaults, in its obfuscated tests.

- [x] 10)
cowplot has a Floating point exception in shared_legends.Rmd.

- [ ] 11)
```
Error in FUN(X[[i]], ...) : object is not coercible to a unit
Calls: blobbogram -> Summary.unit -> unlist -> lapply -> FUN
```
from gemtc.

- [x] 12)
```
Error in unit(3, "grobwidth", data = seg_plot_yaxis_grobs[[longest_segment]]) :
 data must be either NULL, have length 1, or match the length of the final unit vector
Calls: plot_gene_map -> unit
```
from genoPlotR.

- [ ] 13)
```
Error in grid::unit(c(0, 0, 0, marginLength), marginUnit) : Invalid unit
Calls: ggMarginal ... addMainTheme -> <Anonymous> -> find_args -> mget -> <Anonymous>
```
from ggExtra

- [ ] 14)
```
Error in `attributes<-`(x, attr) :
 'names' attribute [2] must be the same length as the vector [1]
Calls: <Anonymous> ... gtable_add_rows -> insert.unit -> unit.c -> [ -> [.unit
```
from ggraph

- [ ] 15)
Error in grid::unit(c(0, 0, 0, marginLength), marginUnit) : Invalid unit
Calls: <Anonymous> ... addMainTheme -> <Anonymous> -> find_args -> mget -> <Anonymous>

from ggstatsplot

- [ ] 16)
```
 Error in unit(x, unit) : Invalid unit
 Calls: grid.export ... as.animUnit -> as.animUnit.numeric -> animUnit -> is.unit -> unit
```
from gridSVG, which I expect is known.

- [ ] 17)
```
Error in (function (cl, name, valueClass)  :
 c("assignment of an object of class “simpleUnit” is not valid for @‘mar’ in an object of class “hexVP”; is(value, \"unit\") is not TRUE", "assignment of an object of class “unit” is not valid for @‘mar’ in an object of class “hexVP”; is(value, \"unit\") is not TRUE", "assignment of an object of class “unit_v2” is not valid for @‘mar’ in an object of class “hexVP”; is(value, \"unit\") is not TRUE")
Calls: plot -> plot -> .local -> hexViewport -> <Anonymous>
```
from hexbin lidR survey

- [ ] 18)
```
Error in unit(as.numeric(arrow$length) * mag, attr(arrow$length, "unit")) :
 Invalid unit
Calls: <Anonymous> ... <Anonymous> -> .fun -> do.call -> <Anonymous> -> f -> unit
```
from metR tmap

- [ ] 19)
```
Warning in check_units(width, unit) :
 Multiple grid::units detected. Casting all to 'unit' argument ('mm').
Warning in check_units(height, unit) :
 Multiple grid::units detected. Casting all to 'unit' argument ('mm').
>
> # With no panels, printing shows the layout
> figure1
Error in grid::unit(., saved_unit) : Invalid unit
Calls: <Anonymous> ... eval -> _fseq -> freduce -> <Anonymous> -> <Anonymous>
```
from multipanelfigure

- [ ] 20)
```
Error in sum(g_tab$widths[[5]], g_tab$widths[[6]], g_tab$widths[[7]]) :
 invalid 'type' (list) of argument
Calls: thresh_forest
```
in nathresh

- [ ] 21)
```
 Error: isTRUE(all.equal(getGrob(result, "MAP"), truth)) is not TRUE
```
in portfolio

- [ ] 22)
```
Error in grid::unit(c(0, 0, 0, marginLength), marginUnit) : Invalid unit
Calls: scatterplot ... addMainTheme -> <Anonymous> -> find_args -> mget -> <Anonymous>
```
in sensitivity

- [ ] 23)
```
Error in matchData[[i]] * amount[i] :
 non-numeric argument to binary operator
Calls: plotSelected ... <Anonymous> -> do.call -> sisalTable -> Summary.unit
```
in sisal and stripless

**Comment by thomasp85** [comment] 2019-04-12 07:49
cc @pmur002

**Comment by thomasp85** [comment] 2019-07-02 08:45
@pmur002 will it be possible to do a CRAN check soonish again with the #1 PR? I've done a fair amount of work to accommodate old units in the new code so that they should be converted transparently, and it would be nice to see how many issues this fix before tackling the remaining part...

**Comment by pmur002** [comment] 2019-07-03 02:41
I am not keen to take this anywhere near the official CRAN until we have things much more under control.  However, I am developing my own testing set up that I can try testing on.  It is based on a Docker image that ...

- installs the rcheckserver metapackage (http://statmath.wu-wien.ac.at/AASC/debian/archive-amd64/) to provide all of the system dependencies
- mounts a directory containing the R source tree with the new-unit patch applied (so that the source tree can be updated and patched, but persists across Docker containers)
- mounts a directory to build R (so that the build persists across Docker containers)
- mounts a directory of installed 'grid' direct reverse dependencies (so that the packages can be updated and persist across Docker containers)
- also mounts a directory of installed 'grid' recursive dependencies, but that is only worth running once we have things much more stable.

I can also run this on a 20-core 64GB machine, so it does not take all day (just a few hours).

I have got this producing something similar to the CRAN failures in the list above, so we can hopefully use it to bring the list of problems down much lower.

Will try to set a test run going with the latest new-unit version.

**Comment by thomasp85** [comment] 2019-07-03 19:31
That sounds good... let me try to fix the problems you reported before you begin testing

**Comment by pmur002** [comment] 2019-07-03 20:24
Ok.  Let me know when you're ready for me to try a test.

**Comment by thomasp85** [comment] 2019-07-04 08:33
I've fixed the problems you identified, so you are free to try out a revdep check

**Comment by pmur002** [comment] 2019-07-05 02:36
Thanks.  My upgradeUnit() tests now work for me (though I had to export the upgradeUnit() methods in NAMESPACE first - I have pushed that change).

**Comment by pmur002** [comment] 2019-07-05 03:09
I am updating my test set up (for latest CRAN package versions).  Will run devdep check next week.

**Comment by pmur002** [comment] 2019-07-19 02:37
Sorry about the delay - teaching prep took over.
I have run a set of checks and unfortunately, it looks like we are not there yet ...
```
Check status summary:
                  ERROR WARN NOTE  OK
  Source packages   294   29   66 106
```
May even be worse than before ?

That is just on direct 'grid' dependencies.  Looking at the first error, it seems like we break 'lattice' straight off the bat.  For example, this fails ...
```
library(lattice)
example(barchart)
```
Do you have time to take a look at that?

the check summary is attached, which is useful for seeing which packages failed.  I can put the full set of check directories up on a dropbox for you if you like, but it is 2GB.  Alternatively, I can provide individual package check directories if you want to take a closer look at anything.

[workResult.txt](https://github.com/thomasp85/grid/files/3409175/workResult.txt)

**Comment by pmur002** [comment] 2019-07-26 00:45
I have tracked the first problem (in 'abd') to a much simpler issue in 'lattice'.  I would say the problem probably also afflicts 'ggplot2' (unconfirmed), which would explain the blow out in package errors (?).
Anyway, the problem is as simple as ...
```
max(unit(1, "strwidth", "test"))
```
... which produces ...
```
Error in upgradeUnit.default(list(list(1, "test", 14L))) : 
  Not a unit object
```
This is traced to the following lines in Summary.unit() ...
```
  x <- unlist(lapply(units, as.unit), recursive = FALSE)
  
  matchUnits <- .Call(C_matchUnit, x, ok)
```
... where the unlist() downgrades the list of "unit" objects in 'x' to a list of plain lists.  C_matchUnit() eventually chokes on that because a plain list is not a "unit" object.  The rest of the code in Summary.unit() appears to be based on a list of "unit" objects, which suggests that the unlist() is wrong, but it does not look like C_matchUnit() is designed for a list of "unit" objects.  I am not sure what the right fix is here - any suggestions?  Is my diagnosis correct ?

**Comment by thomasp85** [comment] 2019-08-05 11:42
I'm back from vacation and will begin working on a fix for this — thanks for the initial digging

**Comment by thomasp85** [comment] 2019-08-05 12:07
If only ever all bugs were this easy to fix :-)

**Comment by pmur002** [comment] 2019-08-06 02:55
Got it.  Thanks.  Will run another grid rev dep check.

**Comment by pmur002** [comment] 2019-08-06 22:34
I am now seeing ...
```
> xyplot(Sepal.Length + Sepal.Width ~ Petal.Length + Petal.Width | Species,
  data = iris, scales = "free", layout = c(2, 2),
  auto.key = list(x = .6, y = .7, corner = c(0, 0)))

Error: index out of bounds ("unit" subsetting)
```
I'm beginning to suspect we should at least get 'lattice' and 'ggplot2' passing R CMD check before I run the larger/longer tests :)

**Comment by thomasp85** [comment] 2019-08-27 12:12
I have fixed the error above and both lattice and ggplot2 now passes tests with the new-unit branch. Can I get you to once more run a full batteri of revdep checks?

**Comment by pmur002** [comment] 2019-08-28 03:41
Thanks!  Will try revdep over next day or two.

**Comment by pmur002** [comment] 2019-09-04 23:09
An interim report to show progress.  We are down to "only" 42 package failures (see below).  I am looking closer at these because there are some suspicious results (e.g., 'ggplot2' reports error, but without the massive cascade of errors to dependent packages).

AeRobiology ... ERROR
analogue ... ERROR
animint2 ... ERROR
bcrm ... ERROR
CARBayes ... ERROR
Cascade ... ERROR
ChainLadder ... ERROR
ChemoSpec ... ERROR
clustrd ... ERROR
clustree ... ERROR
cRegulome ... ERROR
genoPlotR ... ERROR
ggExtra ... ERROR
ggplot2 ... ERROR
ggpol ... ERROR
ggraph ... ERROR
ggrepel ... ERROR
ggResidpanel ... ERROR
ggstatsplot ... ERROR
gprofiler2 ... ERROR
gridSVG ... ERROR
heatwaveR ... ERROR
hexbin ... ERROR
HistDAWass ... ERROR
LDheatmap ... ERROR
lemon ... ERROR
metR ... ERROR
morse ... ERROR
multipanelfigure ... ERROR
NMF ... ERROR
partykit ... ERROR
pheatmap ... ERROR
Plasmidprofiler ... ERROR
portfolio ... ERROR
Rcan ... ERROR
survey ... ERROR
tmap ... ERROR
trelliscopejs ... ERROR
ufs ... ERROR
vcd ... ERROR
vivo ... ERROR
wilson ... ERROR

**Comment by pmur002** [comment] 2019-09-04 23:22
AeRobiology traces back to `plotly:::mm2pixels()`, which is peeking at `attr(u, "unit")` (strike 1), expecting it to always be there for units (strike 2), and expecting it to be a character value (strike 3). `plotly:::verifyUnit()` also peeks at attr(u, "unit").

**Comment by pmur002** [comment] 2019-09-04 23:33
'ggplot2' passes when tested on its own (it had failed on a testthat test reporting non-identical results for some axis labels - not sure what that was, but does not seem to be related to 'grid' units)

**Comment by pmur002** [comment] 2019-09-04 23:40
'analogue' passes when tested on its own (it had failed on LaTeX errors when creating PDF version of manual).  Although I noted that the package version I downloaded manually from CRAN was newer than the one used for the revdep check (same thing for 'ggplot2') so I need to check my scripts that update packages for the revdep check.

**Comment by pmur002** [comment] 2019-09-04 23:55
My script was checking older versions of packages as well as the most recent (so some of those failures were from out-of-date packages).  Rechecking now ...

**Comment by thomasp85** [comment] 2019-09-05 08:29
Well, only 42 including some false positives is def an improvement 🙂

FWIW, the issue with plotly where they inspect the unit is why I added the `unitType()` method. I think it will be easier to get people to update their packages if we provide an easy remedy

**Comment by pmur002** [comment] 2019-09-08 21:49
Good point about your `unitType()` function.  I agree about making it easier for people to fix their packages.  It would be good to start keeping a record of suggested fixes for packages.

Having fixed my checking code, I we are down to 28 problem packages.  However, note that 'AeRobiology' no longer appears (because its failure is in rebuilding vignettes which does not appear in the overall package check result), so we have an underestimate of the impact on CRAN.

```
animint2 ... ERROR
cowplot ... ERROR
genoPlotR ... ERROR
ggpol ... ERROR
ggraph ... ERROR
ggrepel ... ERROR
ggResidpanel ... ERROR
gprofiler2 ... ERROR
gridSVG ... ERROR
heatwaveR ... ERROR
hexbin ... ERROR
LDheatmap ... ERROR
lemon ... ERROR
metR ... ERROR
multipanelfigure ... ERROR
NMF ... ERROR
ParamHelpers ... ERROR
partykit ... ERROR
pheatmap ... ERROR
Plasmidprofiler ... ERROR
portfolio ... ERROR
survey ... ERROR
tmap ... ERROR
trelliscopejs ... ERROR
ufs ... ERROR
vcd ... ERROR
vivo ... ERROR
wilson ... ERROR
```

Will begin working through those.

**Comment by pmur002** [comment] 2019-09-11 03:26
'animint2' seems to be using its own `margin()` function, which is making "unit" objects of its own design.  Fixable by getting 'animint2' to use `ggplot2::margin()` ?

**Comment by pmur002** [comment] 2019-09-11 21:55
'cowplot' dies because this produces a floating point exception ...
```
grid::unit.pmax(grid::unit(1,"cm") + grid::unit(.5, "npc"), NULL)
```
... because within `grid:::pSummary()`, the `NULL` gets through to `summaryUnits()` [unit.c] because `conformingUnits()` [unit.c], which is called by `grid:::identicalUnits()`, bails out as soon as it hits a non-simple unit.
So there needs to be better protection higher up against NULL values.
Could you take a look at where that protection should go (while I continue sifting through the CRAN failures) ?

**Comment by pmur002** [comment] 2019-09-27 02:30
'gprofiler2' traces to the same plotly::mm2pixel() problem as 'AeRobiology'

**Comment by pmur002** [comment] 2019-09-27 02:35
'gridSVG' already has a fix on R-Forge (though that could do with being updated to use unitType() once the new unit stuff is in).

**Comment by pmur002** [comment] 2019-09-27 02:40
'heatwaveR' is another plotly::mm2pixel() problem

**Comment by pmur002** [comment] 2019-09-27 02:54
'hexbin' fails because it generates an S4 class from the S3 unit class.  The following fix seems to clear things up (hexViewport.R) ...
```
setOldClass(c("unit", "unit_v2"))
setOldClass(c("simpleUnit", "unit", "unit_v2"))
```

**Comment by pmur002** [comment] 2019-09-27 03:20
'LDheatmap' is failing in its addTracks.Rnw vignette I think because it loads `system.file("extdata/addTracks.RData",package="LDheatmap")`, which contains some old-style units.  It should be possible to regenerate that .RData file to see if that fixes the problem (the vignette has code), but it is not working for me yet.  

Did we look at trying to detect and "promote" these old-style units to new-style units at some point?

**Comment by thomasp85** [comment] 2019-09-27 07:13
Old style units should get promoted automatically now upon use, even if they are already embedded within a grob or viewport... I’ll look into this one a bit more

**Comment by pmur002** [comment] 2019-10-02 00:37
'lemon' has (in ggplot_gtable.built_lemon()) code like this ...
```
  do.call(grid::unit.pmax, c(widths, gtable$widths[gtable$layout$l[i]]))
```
  ... where the c() call is combining a list of units with a single unit.
  Goodness knows how this ever worked, but now at least that should be
  something like ...
```
  do.call(grid::unit.pmax, 
          c(widths, 
            list(gtable$widths[gtable$layout$l[i]])))
```
  (there are 3 other instances in ggplot_gtable.built_lemon())

**Comment by pmur002** [comment] 2019-10-03 21:23
'metR' has (in geom_arrow.R and slight variation in geom_streamline.R) ...
```
  arrow$length <- unit(as.numeric(arrow$length)*mag, attr(arrow$length, "unit"))
```
  ... which can easily be fixed with ...
```
  arrow$length <- mag*arrow$length
```
  (and that should even work in current R-release so can hopefully be fixed now)

**Comment by pmur002** [comment] 2019-10-03 21:41
'multipanelfigure' has ...
```
  round.unit <- function(x, digits = 0) {
      saved_unit <- x %>%
          attr("unit")
      x %>%
          as.numeric() %>%
          round(digits = digits) %>%
          grid::unit(saved_unit) %>%
      return()
  }
```
  ... (plus a scary-looking `round.unit.list()`), which is clearly peeking
  into unit objects.  

  This could be another case for the new `grid::unitType()` function, 
  though I worry about the `round.unit.list()`;  we may need to look
  at implementing a `grid::round.unit()` method ourselves to make this safe (?)

**Comment by pmur002** [comment] 2019-10-03 22:44
'NMF' fails `example("NMF-package")` with ...
```
  REAL() can only be applied to a 'numeric', not a 'integer'
```
  ... which appears to simply be `REAL(values)` being called on an integer
  (within `multUnits()` in unit.c).

  So, the fix for this one is on us to be more defensive about either
  coping with both INTEGER and REAL in C code, or coercing with
  `as.numeric()` in R code.

**Comment by pmur002** [comment] 2019-10-04 02:20
'ParamHelpers' is seg-faulting because `grid::unit.pmax()` cannot cope with 
  `NULL` values (but it used to).  The following code used to run (for
  better or worse) ...
```
  unit.pmax(unit(c(0, 1), c("in", "mm")), 
            unit(1, "npc"))
  unit.pmax(unit(c(0, 1), c("in", "mm")), 
            NULL, 
            unit(1, "npc"))
```
  ... but now it seg-faults (when the `NULL` is passed to `summaryUnits()`
  then to `unitScalar()`, in unit.c).

  Ours to fix.

**Comment by pmur002** [comment] 2019-10-04 02:22
'partykit' is failing with ...
```
  Start tag expected, '<' not found
```
  ... an 'XML' error ???

  Just retest in next round.

**Comment by pmur002** [comment] 2019-10-04 02:31
'pheatmap' dies with ...
```
  Error in Ops.unit(m, size) : 
    REAL() can only be applied to a 'numeric', not a 'integer'
```
  ... which is just like 'NMF', so hopefully the same problem that
  can be solved by us being more robust about integer multipliers 
  in `x*unit()`.

**Comment by pmur002** [comment] 2019-10-04 02:33
'Plasmidprofiler' is another ggplotly::mm2pixels() case.

**Comment by pmur002** [comment] 2019-10-04 02:37
'portfolio' fails its tests because it is trying to compare with a
  saved grob (which will have old-style units).
```
  load("map.market.test.RData")
  ...
  stopifnot(
            isTRUE(all.equal(getGrob(result, "MAP"), truth))
            )
```
  Solution is hopefully just to regenerate saved `truth`.

**Comment by pmur002** [comment] 2019-10-04 02:40
'survey' failure appears to be due to 'hexbin' (see above).

**Comment by pmur002** [comment] 2019-10-04 02:45
'tmap' has ...
```
  unit_mod <- function(unt, a=0, b=1) {
	cls <- attr(unt, "unit")
	unit(as.numeric(unt)*b + a, cls)
  }
```
  ... which would appear to benefit from the new `grid::unitType()`

**Comment by pmur002** [comment] 2019-10-04 02:46
'trelliscopejs' is another ggplotly::mm2pixels() case.

**Comment by pmur002** [comment] 2019-10-04 02:47
'ufs' fails because it does not have a dependency installed ('bootES')

  I will need to check whether I can install that dependency.

**Comment by pmur002** [comment] 2019-10-04 02:54
'vcd' has a line in `tile.default()` ...
```
   un <-  unit(fac, "npc") - unit(fac * 5 / spacing[[1]][[1]], "lines")
```
   ... where `spacing[[1]][[1]]` ends up with a "unit" object (in our
   new implementation), which fails because it tries to divide by
   a unit object.

**Comment by pmur002** [comment] 2019-10-04 02:56
'vivo' fails with what appears to be an attempt to access an
  unexported symbol from another package ...
```
  'calculate_variable_split' is not an exported object from 'namespace:ingredients
'
```
  See what happens on next revdepcheck ?

**Comment by pmur002** [comment] 2019-10-04 03:03
'wilson' is failing because of `ComplexHeatmap::is_abs_unit()`, which
  peeks into units with things like ...
```
  attr(x, "valid.unit")
```
  So 'ComplexHeatmap' needs fixing.

**Comment by pmur002** [comment] 2019-10-23 19:42
Carson Sievert has merged a fix for `plotly::mm2pixels()` (https://github.com/ropensci/plotly/pull/1646).

**Comment by thomasp85** [comment] 2019-11-04 10:25
I've added fixes to `multUnit()` and `Summary.unit()` which should fix NMF, pheatmap, and ParamHelpers... The remaining listed here should be fixed in their own code IMO

**Comment by thomasp85** [comment] 2019-11-04 10:28
regarding the genoplotr error, I think there is a very strong design reason for enforcing equal length, but backward compatibility probably trumps it for a package like grid so I'll loosen it up

**Comment by thomasp85** [comment] 2019-11-04 10:40
Is there basis for trying another revdepcheck? I feel we are close to the point where we need to start compiling a list of packages we need to contact

**Comment by pmur002** [comment] 2019-11-08 02:45
Thanks Thomas. I had one query about the multUnit() patch (which you have hopefully recevied via github).  Otherwise looks good.  I have begun contacting a couple of package authors (e.g., myself) and getting some fixes onto CRAN already (where possible).  The 'plotly' one underlies several others, so I might wait a few weeks for that fix to get to CRAN before running another revdepcheck.  In the meantime, I might contact a few others where the package fix is simple.

**Comment by pmur002** [comment] 2019-12-03 02:40
I am seeing ...
```
S3method("absolute.units", "unit")
S3method("absolute.units", "unit.list")
S3method("absolute.units", "unit.arithmetic")

S3method("unitType", "unit")
S3method("unitType", "unit.list")
S3method("unitType", "unit.arithmetic")
```
... in the NAMESPACE file in the new-unit branch.  They should not be there (?)

**Comment by thomasp85** [comment] 2019-12-03 11:26
No idea how they crept back in... Maybe due to a merge from SVN

**Comment by thomasp85** [comment] 2019-12-03 11:29
fixed now

**Comment by pmur002** [comment] 2019-12-03 19:35
Thanks!

**Comment by pmur002** [comment] 2019-12-12 21:42
Signs of progress in latest revdepcheck.  Here's the error list ...
```
animint2 ... ERROR
bomrang ... ERROR
cowplot ... ERROR
gg.gap ... ERROR
ggpol ... ERROR
ggraph ... ERROR
lemon ... ERROR
multipanelfigure ... ERROR
ParamHelpers ... ERROR
partykit ... ERROR
portfolio ... ERROR
surveillance ... ERROR
tmap ... ERROR
ufs ... ERROR
vcd ... ERROR
wilson ... ERROR
```
A couple of new ones in there, plus a couple that I thought we had fixed, so I need to look closer. 

But still, progress!

**Comment by thomasp85** [comment] 2019-12-13 11:13
This looks promising… Let me know if you need help triaging through the problems

best
Thomas

**Comment by pmur002** [comment] 2019-12-15 19:52
Thanks.  I wil probably be back with more questions

**Comment by pmur002** [comment] 2020-01-07 22:42
One new failure is from 'gg.gap' (a new package), but it depends on 'cowplot' which is also still failing.  This is a reliable trigger ...
```
library(gg.gap
example(add.legend)
```
The issue appears to be a `NULL` within a unit object being passed in to `summaryUnits()` (unit.c).  You added a fix for `Summary.unit()` (unit.R) to cope with `NULL` values in units, but it looks like this needs protection too (though the fix may not be as simple because we are now dealing with a "parallel" summary rather than an aggregating summary; `pmin()` instead of `min()` ?).

Could you please take a look ?

**Comment by pmur002** [comment] 2020-01-07 22:45
Another failure is 'ggraph' - do you mind if I ask you to take a look at that one ? :)

**Comment by pmur002** [comment] 2020-01-07 22:47
'ParamHelpers' is hopefully the same problem (and fix) as 'cowplot'

**Comment by pmur002** [comment] 2020-01-07 23:05
'ufs' is a red herring.  It passes if I make sure that 'bootES' is installed.

**Comment by pmur002** [comment] 2020-01-07 23:07
'bomrang' failure does not appear to be related to 'grid'

**Comment by pmur002** [comment] 2020-01-07 23:07
'surveillance' failure does not appear to be related to 'grid'

**Comment by pmur002** [comment] 2020-01-07 23:08
'partykit' failure does not appear to be related to 'grid'

**Comment by pmur002** [comment] 2020-01-08 00:36
I have created a PR (https://github.com/mtennekes/tmap/pull/386) for 'tmap' (to fix things by making use of `grid::unitType()`).

**Comment by thomasp85** [comment] 2020-01-08 07:46
I'll look into gg.gap and ggraph - we are getting close

**Comment by thomasp85** [comment] 2020-01-08 07:47
Can I get you to send me the error from ggraph?

**Comment by thomasp85** [comment] 2020-01-08 07:47
and gg.gap for that matter :-)

**Comment by pmur002** [comment] 2020-01-12 19:39
Of course!  Sorry.  Here they are ...

'ggraph':

```
* checking examples ... ERROR
Running examples in ‘ggraph-Ex.R’ failed
The error most likely occurred in:

> ### Name: geom_conn_bundle
> ### Title: Create hierarchical edge bundles between node connections
> ### Aliases: geom_conn_bundle geom_conn_bundle2 geom_conn_bundle0
> 
> ### ** Examples
> 
> # Create a graph of the flare class system
> library(tidygraph)

Attaching package: ‘tidygraph’

The following object is masked from ‘package:stats’:

    filter

> flareGraph <- tbl_graph(flare$vertices, flare$edges) %>%
+   mutate(
+     class = map_bfs_chr(node_is_root(), .f = function(node, dist, path, ...) {
+       if (dist <= 1) {
+         return(shortName[node])
+       }
+       path$result[[nrow(path)]]
+     })
+   )
> importFrom <- match(flare$imports$from, flare$vertices$name)
> importTo <- match(flare$imports$to, flare$vertices$name)
> 
> # Use class inheritance for layout but plot class imports as bundles
> ggraph(flareGraph, 'dendrogram', circular = TRUE) +
+   geom_conn_bundle(aes(colour = stat(index)),
+     data = get_con(importFrom, importTo),
+     edge_alpha = 0.25
+   ) +
+   geom_node_point(aes(filter = leaf, colour = class)) +
+   scale_edge_colour_distiller('', direction = 1, guide = 'edge_direction') +
+   coord_fixed() +
+   ggforce::theme_no_axes()
Error in `attributes<-`(x, attr) : 
  'names' attribute [2] must be the same length as the vector [1]
Calls: <Anonymous> ... gtable_add_rows -> insert.unit -> unit.c -> [ -> [.unit
Execution halted
```

**Comment by pmur002** [comment] 2020-01-12 19:40
'gg.gap':
```
* checking examples ... ERROR
Running examples in ‘gg.gap-Ex.R’ failed
The error most likely occurred in:

> ### Name: add.legend
> ### Title: Add Legend to gg.gap()
> ### Aliases: add.legend
> 
> ### ** Examples
> 
> library(ggplot2)
> mtcars$gear <- factor(mtcars$gear)
> bp <- ggplot(data = mtcars, aes(x = gear, fill = gear)) +
+     geom_bar() +
+     ggtitle("Number of Cars by Gear") +
+     xlab("Gears")
> gg.gap(plot = bp,
+        ylim = c(0,16),
+        segments = c(6,8))
Floating point exception (core dumped)
```

**Comment by pmur002** [comment] 2020-01-12 22:22
I have emailed David Meyer about 'vcd' with the following suggested fix.

   I tested the following code change (in tile.R), from ...

```
    un <-  unit(fac, "npc") - unit(fac * 5 / spacing[[1]][[1]], "lines")
```
   ... to ...
```
    un <-  unit(fac, "npc") -
        unit(fac * 5 / convertWidth(spacing[[1]], "lines",
                                    valueOnly=TRUE),
             "lines")
```
  Should be fixed if the above change is merged and sent to CRAN.

**Comment by pmur002** [comment] 2020-01-13 21:53
'wilson' is failing because of `ComplexHeatmap::is_abs_unit()`, which
peeks into units with things like ...
```
  attr(x, "valid.unit")
```
Added `recurse` argument to `unitType()` to hopefully provide enough "official" information for `ComplexHeatmap::is_abs_unit()` to work with.

**Comment by thomasp85** [comment] 2020-01-22 15:47
gg.gap is failing because through cowplot because it ends up with a zero-length unit vector. Constructing such a vector has never been allowed but it was never checked during subsetting. My feeling is we should enforce it during subsetting as well. This will (continue to) break gg.gap but it should never have worked in the first place. Thoughts?

**Comment by thomasp85** [comment] 2020-01-22 18:59
gg.gap is fixed. I initially mischaracterised the problem, but we should still explicitly forbid the creation of zero-length unit vectors through indexing

**Comment by thomasp85** [comment] 2020-01-22 19:15
I cannot seem to get all the dependencies of ggraph to work on r-devel, so this fix is a bit in the blind. Based on the error message it looks like ggraph is subsetting a named unit vector. The `names` attribute was not subsetted along with it which led to the error. This has been fixed, but if you can confirm that both ggraph and gg.gap works now it would be great

**Comment by pmur002** [comment] 2020-01-29 01:38
Two steps forward ... looks like gg.gap is fixed, but not 'ggraph'.  Some new ones there too (e.g., 'gridtext').  Will follow up with more detail (though away for next two weeks, so there will be a pause).
```
animint2 ... ERROR
blorr ... ERROR
ggpol ... ERROR
ggraph ... ERROR
gridtext ... ERROR
lemon ... ERROR
multipanelfigure ... ERROR
portfolio ... ERROR
prophet ... ERROR
tidybayes ... ERROR
trelliscopejs ... ERROR
walkr ... ERROR
wilson ... ERROR
```

**Comment by pmur002** [comment] 2020-01-29 01:43
Error from 'ggraph':
```
* checking examples ... ERROR
Running examples in ‘ggraph-Ex.R’ failed
The error most likely occurred in:

> ### Name: geom_edge_parallel
> ### Title: Draw multi edges as parallel lines
> ### Aliases: geom_edge_parallel geom_edge_parallel2 geom_edge_parallel0
> 
> ### ** Examples
> 
> require(tidygraph)
Loading required package: tidygraph

Attaching package: ‘tidygraph’

The following object is masked from ‘package:stats’:

    filter

> gr <- create_notable('bull') %>%
+   convert(to_directed) %>%
+   bind_edges(data.frame(from = c(1, 2, 2, 3), to = c(2, 1, 3, 2))) %E>%
+   mutate(class = sample(letters[1:3], 9, TRUE)) %N>%
+   mutate(class = sample(c('x', 'y'), 5, TRUE))
> 
> ggraph(gr, 'stress') +
+   geom_edge_parallel(aes(alpha = stat(index)))
> 
> ggraph(gr, 'stress') +
+   geom_edge_parallel2(aes(colour = node.class))
> 
> ggraph(gr, 'stress') +
+   geom_edge_parallel0(aes(colour = class))
Error: Cannot create zero-length unit vector ("unit" subsetting)
Execution halted
```
So that's just your new protection working(?).

**Comment by thomasp85** [comment] 2020-02-03 08:25
Yeah - is ggraph the only package provoking the new error?

**Comment by thomasp85** [comment] 2020-02-06 13:07
@pmur002 do you think it makes sense to allow 0-length units instead? the lack of 0-length versions is quite different than standard R vector behaviour...

**Comment by thomasp85** [comment] 2020-02-06 13:59
I've fixed the bug in ggraph. If no problems in other packages surfaces with the more stringent indexes lets just keep the current behaviour

**Comment by pmur002** [comment] 2020-02-17 00:52
Yes, it appears that 'ggraph' was the only one provoking 'Cannot create zero-length unit vector' and thanks for the fix; that works for me.

**Comment by pmur002** [comment] 2020-02-20 02:13
'blorr' error was not related to 'grid' (version 0.2.2 passes CMD check)

**Comment by pmur002** [comment] 2020-02-20 02:21
'gridtext' is being particularly naughty and generating 'grid' unit objects by hand *in C code*.
This will require discussion with the package author.

**Comment by pmur002** [comment] 2020-02-20 02:27
'Prophet' error does not look related to 'grid' to me.

**Comment by pmur002** [comment] 2020-02-20 02:34
'trelliscope' error did not appear to be related to 'grid' and new version (2.0.1) passes CMD check

**Comment by pmur002** [comment] 2020-02-20 02:38
'walkr' was removed from CRAN on 2019-12-21 ("check problems were not corrected in time")

**Comment by pmur002** [comment] 2020-02-20 02:39
'trelliscope' error did not appear to be related to 'grid' and new version (0.2.4) passes CMD check

**Closed** 2020-04-21 06:21 UTC
